name: Common Pipeline Steps

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    uses: niqzart/ca-actions/.github/workflows/full-workflow.yml@v1.0
    with:
      python_version: 3.11
      install_command: pip install -r requirements-dev.txt
      lint_directory: carp
      config_file: setup.cfg
      pytest_workdir: carp
